creation_rules:
  # Encrypt any files under ops/secrets/ by default.
  - path_regex: ops/secrets/.*\.(env|json|txt|enc)$
    encrypted_regex: '^(data|stringData|secrets|env|content)$'
    # Replace with your age recipient (public key), e.g. "age1...".
    age:
      - "age17cmmft74use5kyqndrktpjpw4ahmwhqzjk9ml4xfyut37hlg8utshmh7q3"

