// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27EA4v032qzE56j7zk7mLN553yeBwEqs',
    appId: '1:714495385281:web:49a759dfa4843f4b633e40',
    messagingSenderId: '714495385281',
    projectId: 'ub-neyvo',
    authDomain: 'ub-neyvo.firebaseapp.com',
    storageBucket: 'ub-neyvo.firebasestorage.app',
    measurementId: 'G-0YJK8XR114',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpFRXVL__5c_Et5kRtvuHHx3FDXnkV8U',
    appId: '1:714495385281:android:c565f760085b6744633e40',
    messagingSenderId: '714495385281',
    projectId: 'ub-neyvo',
    storageBucket: 'ub-neyvo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSh-endeLxI6b97BgsUhkA4ZcvzBBBdNU',
    appId: '1:714495385281:ios:9778133ed7f25c2c633e40',
    messagingSenderId: '714495385281',
    projectId: 'ub-neyvo',
    storageBucket: 'ub-neyvo.firebasestorage.app',
    iosBundleId: 'com.neyvo.pulse.neyvoPulseFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSh-endeLxI6b97BgsUhkA4ZcvzBBBdNU',
    appId: '1:714495385281:ios:9778133ed7f25c2c633e40',
    messagingSenderId: '714495385281',
    projectId: 'ub-neyvo',
    storageBucket: 'ub-neyvo.firebasestorage.app',
    iosBundleId: 'com.neyvo.pulse.neyvoPulseFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC27EA4v032qzE56j7zk7mLN553yeBwEqs',
    appId: '1:714495385281:web:ee2ef48f67f16663633e40',
    messagingSenderId: '714495385281',
    projectId: 'ub-neyvo',
    authDomain: 'ub-neyvo.firebaseapp.com',
    storageBucket: 'ub-neyvo.firebasestorage.app',
    measurementId: 'G-T7MMXB6WZ0',
  );

}