// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUsbak1y49OtCYV2V6wdXL6YW0Rin2AM',
    appId: '1:151387636667:web:0239fe9b2f98d6773eba9e',
    messagingSenderId: '151387636667',
    projectId: 'neyvo-launch',
    authDomain: 'neyvo-launch.firebaseapp.com',
    storageBucket: 'neyvo-launch.firebasestorage.app',
    measurementId: 'G-3Q80BLPH93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1sO8dQ-gaE6Jab8BKgeQp9cApPH7KPo',
    appId: '1:151387636667:android:0ac4f76bc37c98d53eba9e',
    messagingSenderId: '151387636667',
    projectId: 'neyvo-launch',
    storageBucket: 'neyvo-launch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSQNw_8OvYoKtMJb_xpRaY8Yl1bBGAuWI',
    appId: '1:151387636667:ios:66aae9468e89fa433eba9e',
    messagingSenderId: '151387636667',
    projectId: 'neyvo-launch',
    storageBucket: 'neyvo-launch.firebasestorage.app',
    iosBundleId: 'com.neyvo.pulse.neyvoPulseFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSQNw_8OvYoKtMJb_xpRaY8Yl1bBGAuWI',
    appId: '1:151387636667:ios:66aae9468e89fa433eba9e',
    messagingSenderId: '151387636667',
    projectId: 'neyvo-launch',
    storageBucket: 'neyvo-launch.firebasestorage.app',
    iosBundleId: 'com.neyvo.pulse.neyvoPulseFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFUsbak1y49OtCYV2V6wdXL6YW0Rin2AM',
    appId: '1:151387636667:web:7d2ca9e4132b01de3eba9e',
    messagingSenderId: '151387636667',
    projectId: 'neyvo-launch',
    authDomain: 'neyvo-launch.firebaseapp.com',
    storageBucket: 'neyvo-launch.firebasestorage.app',
    measurementId: 'G-PT81W4Z07T',
  );

}
