// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_eCqy1mtNEW2wJr1-E0EBVOoVnOUwKtw',
    appId: '1:109192459806:web:aefc9be4f96aafe16c200f',
    messagingSenderId: '109192459806',
    projectId: 'neyvo-ub-render-front',
    authDomain: 'neyvo-ub-render-front.firebaseapp.com',
    storageBucket: 'neyvo-ub-render-front.firebasestorage.app',
    measurementId: 'G-38RHDWY8D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC50iignZKs2riTpY_WlV-jaOAgiYysrbw',
    appId: '1:109192459806:android:99ea0b589e75782b6c200f',
    messagingSenderId: '109192459806',
    projectId: 'neyvo-ub-render-front',
    storageBucket: 'neyvo-ub-render-front.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSfbuq6be0HJ2y2cIHxc3hNj9GHMoh6UQ',
    appId: '1:109192459806:ios:12c0ed717b9b9f0f6c200f',
    messagingSenderId: '109192459806',
    projectId: 'neyvo-ub-render-front',
    storageBucket: 'neyvo-ub-render-front.firebasestorage.app',
    iosBundleId: 'com.neyvo.pulse.neyvoPulseFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSfbuq6be0HJ2y2cIHxc3hNj9GHMoh6UQ',
    appId: '1:109192459806:ios:12c0ed717b9b9f0f6c200f',
    messagingSenderId: '109192459806',
    projectId: 'neyvo-ub-render-front',
    storageBucket: 'neyvo-ub-render-front.firebasestorage.app',
    iosBundleId: 'com.neyvo.pulse.neyvoPulseFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_eCqy1mtNEW2wJr1-E0EBVOoVnOUwKtw',
    appId: '1:109192459806:web:0881bd20dc48c63b6c200f',
    messagingSenderId: '109192459806',
    projectId: 'neyvo-ub-render-front',
    authDomain: 'neyvo-ub-render-front.firebaseapp.com',
    storageBucket: 'neyvo-ub-render-front.firebasestorage.app',
    measurementId: 'G-LM2D8DVDRF',
  );

}