#!/usr/bin/env node
/**
 * Generates lib/firebase_options.dart for goodwin-neyvo using:
 * - android/app/google-services.json (Android)
 * - ios/Runner/GoogleService-Info.plist (iOS/macOS, optional)
 * - Hardcoded goodwin-neyvo web config (web + Windows)
 *
 * Run from GU_Neyvo_Front: node scripts/generate_firebase_options.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

// Goodwin-neyvo web config (already correct in firebase_options.dart)
const WEB_CONFIG = {
  apiKey: 'AIzaSyBUCuj67BNk91FP6CH3TDKlQ1B7hWkZfYk',
  appId: '1:175705543820:web:8482abc223a117208017a9',
  messagingSenderId: '175705543820',
  projectId: 'goodwin-neyvo',
  authDomain: 'goodwin-neyvo.firebaseapp.com',
  storageBucket: 'goodwin-neyvo.firebasestorage.app',
  measurementId: 'G-P12H1JF82D',
};

function readPlistKey(plistText, key) {
  const re = new RegExp(`<key>${key}</key>\\s*<string>([^<]*)</string>`, 'i');
  const m = plistText.match(re);
  return m ? m[1].trim() : null;
}

function main() {
  // Android: from google-services.json
  const googleServicesPath = path.join(ROOT, 'android', 'app', 'google-services.json');
  let android = null;
  if (fs.existsSync(googleServicesPath)) {
    const data = JSON.parse(fs.readFileSync(googleServicesPath, 'utf8'));
    const projectId = data.project_info?.project_id;
    const projectNumber = data.project_info?.project_number;
    const storageBucket = data.project_info?.storage_bucket || `${projectId}.firebasestorage.app`;
    const client = data.client?.[0];
    const appId = client?.client_info?.mobilesdk_app_id;
    const apiKey = client?.api_key?.[0]?.current_key;
    if (projectId && appId && apiKey) {
      android = {
        apiKey,
        appId,
        messagingSenderId: projectNumber,
        projectId,
        storageBucket,
      };
      if (projectId !== 'goodwin-neyvo') {
        console.warn('Warning: android/app/google-services.json is for project "%s". Replace with goodwin-neyvo config from Firebase Console.', projectId);
      }
    }
  }
  if (!android) {
    console.error('Could not read Android config from android/app/google-services.json. Ensure the file exists and is for goodwin-neyvo.');
    process.exit(1);
  }

  // iOS/macOS: from GoogleService-Info.plist
  const plistPath = path.join(ROOT, 'ios', 'Runner', 'GoogleService-Info.plist');
  let ios = null;
  if (fs.existsSync(plistPath)) {
    const plistText = fs.readFileSync(plistPath, 'utf8');
    const apiKey = readPlistKey(plistText, 'API_KEY');
    const appId = readPlistKey(plistText, 'GOOGLE_APP_ID');
    const projectId = readPlistKey(plistText, 'PROJECT_ID');
    const messagingSenderId = readPlistKey(plistText, 'GCM_SENDER_ID');
    const storageBucket = readPlistKey(plistText, 'STORAGE_BUCKET');
    const iosBundleId = readPlistKey(plistText, 'BUNDLE_ID');
    if (apiKey && appId && projectId) {
      ios = {
        apiKey,
        appId,
        messagingSenderId: messagingSenderId || '',
        projectId,
        storageBucket: storageBucket || `${projectId}.firebasestorage.app`,
        iosBundleId: iosBundleId || 'com.neyvo.pulse.neyvoPulseFront',
      };
    }
  }
  if (!ios) {
    console.warn('No ios/Runner/GoogleService-Info.plist (or invalid). iOS/macOS will use Android config as fallback. Add iOS app in goodwin-neyvo and download plist for full support.');
    ios = { ...android, iosBundleId: 'com.neyvo.pulse.neyvoPulseFront' };
  }

  const dart = `// File generated by scripts/generate_firebase_options.js for goodwin-neyvo.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps (goodwin-neyvo).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '${WEB_CONFIG.apiKey}',
    appId: '${WEB_CONFIG.appId}',
    messagingSenderId: '${WEB_CONFIG.messagingSenderId}',
    projectId: '${WEB_CONFIG.projectId}',
    authDomain: '${WEB_CONFIG.authDomain}',
    storageBucket: '${WEB_CONFIG.storageBucket}',
    measurementId: '${WEB_CONFIG.measurementId}',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '${android.apiKey}',
    appId: '${android.appId}',
    messagingSenderId: '${android.messagingSenderId}',
    projectId: '${android.projectId}',
    storageBucket: '${android.storageBucket}',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '${ios.apiKey}',
    appId: '${ios.appId}',
    messagingSenderId: '${ios.messagingSenderId}',
    projectId: '${ios.projectId}',
    storageBucket: '${ios.storageBucket}',
    iosBundleId: '${ios.iosBundleId}',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '${ios.apiKey}',
    appId: '${ios.appId}',
    messagingSenderId: '${ios.messagingSenderId}',
    projectId: '${ios.projectId}',
    storageBucket: '${ios.storageBucket}',
    iosBundleId: '${ios.iosBundleId}',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '${WEB_CONFIG.apiKey}',
    appId: '${WEB_CONFIG.appId}',
    messagingSenderId: '${WEB_CONFIG.messagingSenderId}',
    projectId: '${WEB_CONFIG.projectId}',
    authDomain: '${WEB_CONFIG.authDomain}',
    storageBucket: '${WEB_CONFIG.storageBucket}',
    measurementId: '${WEB_CONFIG.measurementId}',
  );
}
`;

  const outPath = path.join(ROOT, 'lib', 'firebase_options.dart');
  fs.writeFileSync(outPath, dart, 'utf8');
  console.log('Written:', outPath);
  console.log('Android projectId:', android.projectId);
  console.log('iOS/macOS projectId:', ios.projectId);
  console.log('Web/Windows projectId: goodwin-neyvo');
}

main();
